[package]
org = "wso2"
name = "mssql_detection"
version = "0.1.0"
distribution = "2201.12.2"

[[dependency]]
org="ballerinax"
name="cdc"
version="0.1.0"
repository="local"

[[dependency]]
org="ballerinax"
name="cdc.mssql.driver"
version="0.1.0"
repository="local"
